config/routes.rb
IceMail::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :messages do
    member do
      patch :status
      get :send_message
      post :message_user
    end
    collection do
      get :sorting
      post :check
      get :sorting_by_month
    end
  end

  devise_for :users
  get "persons/profile", as: 'user_root'

  root 'persons#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  validates :email, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  paginates_per 15
  include AASM

  scope :for_user, ->(user) { where(user_id: user.id) }
  scope :for_state, ->(state) { where(aasm_state: state) }
  aasm do
    state :new, :initial => true
    state :working, :completed, :not_relevanted

    event :work do
      transitions :from => :new, :to => :working
    end

    event :complete do
      transitions :from => :working, :to => :completed
    end

    event :not_relevanted do
      transitions :from => [:new, :working], :to => :not_relevanted
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :set_locale
def set_locale
  I18n.locale = params[:locale] || I18n.default_locale
end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy, :status ]
  before_filter :authenticate_user!
  before_filter :collect_states, only: [:create, :message_user, :index, :sorting, :sorting_by_month]
  before_filter :for_user, only: [:edit, :create, :send_message, :message_user, :index, :sorting, :sorting_by_month]
  before_filter :group_state, only: [:create, :message_user, :index, :sorting]

  # GET /messages
  # GET /messages.json

  def index
  end

  def offseted_time(offset)
    @time_beginning = Time.now.beginning_of_month-offset.months
  end

  def sorting_by_month
    @messages = []
    6.times.each do |i|
      @messages[i] = [offseted_time(i), @for_user.where(created_at: (offseted_time(i)).to_s..(offseted_time(i) + 1.month).to_s).group_by { |hsh| hsh[:aasm_state] }]
    end
    @chart = @for_user.group(:aasm_state).group_by_month(:created_at, range: 6.month.ago.midnight..Time.now).count
  end

  def status
    if @message.working?
      @message.complete
    elsif @message.new?
      @message.work
    end
    render 'edit'
  end

  def send_message
  end

  def message_user
    message = @for_user.find_by(id: params[:id])
    return redirect_to :index unless message
    UserMailer.message_to_the_user(message.email, params[:message_user]).deliver
    render 'index'
  end

  def sorting
    if params[:sort] == 'aasm_state'
      @messages = []
      @states.each do |status|
        @messages += @for_user.for_state(status)
      end
      @messages = Kaminari.paginate_array(@messages).page(params[:page]).per(15)
    else
      @messages = @for_user.order(params[:sort]).page params[:page]
    end
    render 'index'
  end

  def check
    @message = Message.find_by(email: params[:checking_email])
  end


  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
    message = @for_user.find_by(id: params[:id])
    return redirect_to :index unless message
    @available_states = [[message.aasm_state, message.aasm_state]]
    @available_states += message.aasm.states(permitted:true).map{|state|[state.name,state.name]}
  end

  # POST /messages
  # POST /messages.json
  def create
    @message =  current_user.messages.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: I18n.t('message_created') }
        format.json { head :no_content }
        format.js {}
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
        format.js { render partial: 'message_errors'  }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to messages_path, notice: I18n.t('message_updated') }
        format.json { head :no_content }
        format.js {}
      else
        format.html { render action: 'edit' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    def for_user
      @for_user = Message.for_user(current_user)
      @messages = @for_user.order(created_at: :desc).page(params[:page])
    end

    def collect_states
      @states = Message.aasm.states.map{|state| state.name.to_s}
    end

    def group_state
      @group_state = @for_user.group(:aasm_state).count
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:employee, :url, :email, :commit, :time_now, :aasm_state)
    end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title = I18n.t('icemail')
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body
    nav.navbar
      .container
        .row
          .col-md-1 = link_to image_tag("message.png"), messages_path, title:  I18n.t('message')
          .col-md-1 = link_to image_tag("home.png"), user_root_path, title: I18n.t('home')
          .col-md-7
          - if user_signed_in?
            .col-md-2 = current_user.email
            .col-md-1 = link_to image_tag("logout.png"), destroy_user_session_path, :method => :delete, title: I18n.t('logout')
          - else
            .col-md-1 = link_to I18n.t('login'), new_user_session_path
            .col-md-1 = I18n.t('or')
            .col-md-1 = link_to I18n.t('sign_up'), new_user_registration_path

    = yield

app/views/messages/_cycle_message.html.slim
- @messages.each do |message|
  .row.border_my.background_string id="message-#{message.id}"
    = render 'message', message: message
.row.text_centr
  .col-md-12 = paginate(@messages)

app/views/messages/_edit.html.slim
.container.background_modal_window.non_padding_modal
  .modal-header.gradient_green1
    .text_right = link_to I18n.t('×'), messages_path
    h3.text_centr id='myModalLabel' = I18n.t('edit')
  .modal-body.non_padding
    = render 'form', modal: true
  .modal-footer.non_padding
    footer.gradient_green1

app/views/messages/_form.html.slim
modal ||= false
= form_for(@message, remote: modal) do |f|

  - if @message.errors.any?
    #error_explanation
      .container.error_background
        .row
          .col-md-12
            =' pluralize(@message.errors.count, 'error')
            = I18n.t('prohibited_this_message_from_being_saved')
          ul
            - @message.errors.full_messages.each do |msg|
              li = msg
  .container.backdround_lightgray.border_my
    .row
      .field
        .col-md-3
        .col-md-2 = f.label I18n.t('employee')
        .col-md-1 = f.text_field :employee
        .col-md-6

    .row
      .field
        .col-md-3
        .col-md-2 = f.label I18n.t('url')
        .col-md-1 = f.text_field :url
        .col-md-6

    .row
      .field
        .col-md-3
        .col-md-2 = f.label I18n.t('email')
        .col-md-1 = f.text_field :email
        .col-md-6

    .row
      .field
        .col-md-3
        .col-md-2 = f.label I18n.t('commit')
        .col-md-1 = f.text_area :commit
        .col-md-6

    - unless @message.new_record?
      .row
        .field
          .col-md-3
          .col-md-2 = f.label I18n.t('aasm_state')
          .col-md-1 = f.select :aasm_state, @available_states
          .col-md-6
    .row
      .actions
        .col-md-3
        .col-md-2 = f.submit
        .col-md-7

app/views/messages/_message.html.slim
.col-md-1 = message.employee
.col-md-2 = truncate(message.url,length: 20)
.col-md-2 = truncate(message.email,length: 25)
.col-md-3.center = truncate(message.commit,length: 40)
.col-md-1.small = I18n.l(message.created_at, format: :long)
.col-md-1 = message.aasm_state
.col-md-2
  .btn-group = link_to image_tag('show.png'), message, {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', title: I18n.t('show')}
  .btn-group = link_to image_tag('edit.png'), edit_message_path(message), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', title: I18n.t('edit')}
  .btn-group = link_to image_tag('delete.png'), message, title: I18n.t('destroy'), method: :delete, data: { confirm: I18n.t('are_you_sure?') }
  .btn-group = link_to image_tag('send_message.png'), send_message_message_path(message.id), title: I18n.t('send_message')

app/views/messages/_message_errors.js.erb
$("#errors_message").html("<%= j @message.errors.full_messages.to_sentence %>");

app/views/messages/_show.html.slim
.container.background_modal_window.non_padding_modal
  .modal-header.gradient_green1
    .text_right = link_to I18n.t('×'), messages_path
    h3.text_centr id="myModalLabel" = I18n.t('show')
  .modal-body.non_padding
      .backdround_lightgray.border_my
        .row
          .col-md-3
          .col-md-1 = I18n.t('employee')
          .col-md-8 = @message. employee

        .row
          .col-md-3
          .col-md-1 = I18n.t('url')
          .col-md-8  = @message.url

        .row
          .col-md-3
          .col-md-1 = I18n.t('email')
          .col-md-8  = @message.email

        .row
          .col-md-3
          .col-md-1 = I18n.t('commit')
          .col-md-7.word-wrap = @message.commit
          .col-md-1
  .modal-footer.non_padding
    footer.gradient_green1

app/views/messages/check.html.slim
.container.container_top
  .row
    .col-md-5
    .col-md-7 = I18n.t('listing_employee')

  - if @message.present?
    .row.backdround_lightgray.border_my
      .col-md-3
      .col-md-3 = I18n.t('employee_processed_email')
      .col-md-6 = I18n.t('email')

    .row.backdround_lightgray.border_my
      .col-md-4
      .col-md-2 = @message.employee
      .col-md-6 = @message.email
  - else
    .row.error_background
      .col-md-5
      .col-md-7 = I18n.t('not_processed_email')
footer.gradient_green1
  .container
    .row
      .col-md-2 = link_to I18n.t('back'), messages_path
      .col-md-7

app/views/messages/edit.html.slim
.container_top
  .container.border_my
    .row
      .col-md-4
      .col-md-4 = I18n.t('editing_message')
      .col-md-4

  = render 'form'

  footer.gradient_green1
    .container
      .row
        .col-md-12
          .btn-group
            .btn = link_to I18n.t('show'), @message
            .btn = link_to I18n.t('back'), messages_path

app/views/messages/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'messages/edit') %>");
$("#modal-window").show();

app/views/messages/index.html.slim
div id='modal-window' class="modal background_gray " role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'
.container.container_top
  .row
    .col-md-1 = link_to image_tag("new_message.png"), new_message_path, {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', title: I18n.t('new_message')}
    .col-md-4
    .col-md-2 = I18n.t('listing_messages')
    .col-md-2
    .col-md-3
      = form_tag(check_messages_path) do
        .field
          = text_field_tag :checking_email
          = submit_tag I18n.t('Check')
  .row.gradient_green
    .col-md-1 = I18n.t('employee')
    .col-md-2 = I18n.t('url')
    .col-md-2 = I18n.t('email')
    .col-md-2 = I18n.t('commit')
    .col-md-2.padding_center = link_to I18n.t('time_of_creation'), sorting_messages_path(sort: 'created_at')
    .col-md-1 = link_to I18n.t('state'), sorting_messages_path(sort: 'aasm_state')
    .col-md-1 = I18n.t('action')
    .col-md-1
.container.container_centr id='cycle_message'
  = render 'cycle_message'
.container.container_bot
  .container
    .row.capitalize
      - @states.each do |state|
        .col-md-2
          = state
          br
          = @group_state[state] || 0
      .col-md-4.em = link_to I18n.t('show_data_of_the_last_6_months_group(p)ed_by_status'), sorting_by_month_messages_path
    .row

app/views/messages/new.html.slim
.container_top
  .container.border_my
    .row
      .col-md-3
      .col-md-2= I18n.t('new_message')
      .col-md-7
  = render 'form', modal: true
  footer.gradient_green1
    .container
      .row
        .col-md-3
        .col-md-2= link_to I18n.t('back'), messages_path
        .col-md-7

app/views/messages/new.js.erb
$("#modal-window").html("<%= escape_javascript(render 'messages/new') %>");
$("#modal-window").show();

app/views/messages/show.js.erb
$("#modal-window").html("<%= escape_javascript(render 'messages/show') %>");
$("#modal-window").show();

app/views/messages/update.js.erb
$("#message-<%= @message.id %>").html("<%= j render partial: 'message', locals: { message: @message } %>");
$('#modal-window').hide();

app/views/persons/profile.html.slim
h1 = I18n.t('persons_profile')

p Find me in app/views/persons/profile.html.erb
p.notice = notice
p.alert = alert
= link_to I18n.t('new_message'), new_message_path